### PR TITLE
Add { and } motion support

### PR DESCRIPTION
**Pull request by erig0**
- Add { and } motion support.
- Add test for { and }, but I was not able to run the tests. Apologies if the tests don't work.
- Update README to list y,{,}

### CODE REVIEW

**Comment by jugglerchris** [comment]
Thank you again!  I fixed the test - thanks for adding that too!
There was only one obvious issue - it's an exclusive motion (I checked the vim manual).

**Comment by jugglerchris** [comment]
By the way, what was the problem running the tests?

I'm not surprised they didn't run, but I guess it'd be nice if they worked for other people too!

**Comment by erig0** [comment]
I'm using NetBSD's 6.1 release version of tmux (v1.5). It does not have Command Mode (-C) support.
BSD tail also does not support any of the GNU long options.

When I get some time I will install a newer tmux and GNU tail, then try to run them again.

**Comment by jugglerchris** [comment]
Aha, ok - it does need a recent tmux.  I've thought about using something like http://luarocks.org/modules/luarocks/lpty to launch the embedded textadept in a cleaner way, but it's low on the priority list!
The use of the tail options isn't critical.  --follow=name could be "-F" (according to online man pages it's the same in NetBSD and GNU).  "--pid=..." could be replaced with "press ^C when it gets to the end" in the short term!

**Pull request merged**
