### PR TITLE
Improve running the test suite.

### PR DESCRIPTION
**Pull request by mfxmfx**

### CODE REVIEW

**Comment by mfxmfx** [comment]
After applying the above patch all tests pass on my machine, except this one. Any ideas?

Thanks,
Markus

```
cosim_regs...Fail: ./userhome/../scripts/test.lua:554: Failed assertion: [["two three four five
hey bee cee dee ee eff
some miscellaneous text
o#one 
hey ne 
hey 
"]] != [["two three four five
hey bee cee dee ee eff
some miscellaneous text
one hey #one hey 
"]]
```

**Comment by jugglerchris** [comment]
I can confirm I get the same error.  Looking into it!

**Comment by jugglerchris** [comment]
Removing the -u  option makes the test pass (unsurprisingly), but pasting the contents of my .vimrc into the new vimrc doesn't help.  Strange...  I'll have a closer look later.

**Comment by jugglerchris** [comment]
It was a (no)compatible thing, fixed by using -N on the vim command line. Thanks! I changed the test locale too, hope you don't mind. :-)

Thanks for the improvement!

**Pull request merged**
